### ISSUE TITLE
Publish .sublime-package

### ISSUE THREAD

**Issue by mcandre** [sixty4k/st2-zonefile#15]
Please publish a .sublime-package, and include installation steps in the README.

**Comment by sixty4k** [comment]
Hoping to get some time to close out issues soon, as a sidestep for the moment, this is in Package Control, under 'Bind Zone files'.  


https://packagecontrol.io/packages/Bind%20Zone%20files

**Comment by sixty4k** [comment]
(pull requests are always welcome)

**Comment by mcandre** [comment]
Package Control works, thank you!

**Comment by sixty4k** [comment]
Will leave ticket open so that I remember to update the README with that fact.  :D
